### ISSUE TITLE
Bad RPC structure for token authentication

### ISSUE THREAD

**Issue by kkartaltepe** [isundaylee/aria2-ruby#2]
The token for authentication is part of the parameters of every function call. As such it should be pushed at the beginning of the params list.

For me it worked to change https://github.com/isundaylee/aria2-ruby/blob/master/lib/aria2.rb#L212 to
```ruby
params_encoded = Base64.encode64(JSON.generate(params.unshift("token:#{@token}"))
```
Removing the following if statement that checks for a token being set which is safe even when not using --rpc-secret as per the aria2 docs https://aria2.github.io/manual/en/html/aria2c.html#rpc-authorization-secret-token

**Comment by isundaylee** [comment]
Sounds reasonable! However I haven't been maintaining/using this for a long while. Do you mind creating a pull request with that change? 

Thanks ;)

**Comment by kkartaltepe** [comment]
Sure I can make a PR related to this. I also would like to get code from the fork using rest_client pulled in if you would accept it. In my short stint I wasn't able to get torrent adding working with the current get calls.
